#tomcat port
#server:
#  port: 6379
#  url: localhost
#  address: shenzhen
#  servlet:
#    context-path: /demo
#app context
#server.servlet.context-path=/demo
my:
  url: localhost
  port: 6379
  address: shenzhen
  myservers2:
    -1
    -2
    -3
myservers: 1,2,3
